# Sample .travis.yml for R projects

language: r
cache: packages
sudo: false

r:
  - oldrel
  - release
  - devel

after_success:
- Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
on_failure: change
